apiVersion: v1
kind: Service
metadata:
  name: invoice-pdf-api-service
spec:
  type: LoadBalancer
  selector:
    app: invoice-pdf-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
